modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="the_cyan_mod"
version="1.2"
displayName="The Cyan Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="osfanbuff63, MCreator"

[[dependencies.the_cyan_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




